### ISSUE TITLE
log4j errors/ linking errors

### ISSUE THREAD

**Issue by SMT-Ryan** [rpi-ws281x/rpi-ws281x-java#2]
Matt,

when I drop 

log4j-1.2.17.jar
rpi-ws281x-java-1.1.0-SNAPSHOT-javadoc.jar
rpi-ws281x-java-1.1.0-SNAPSHOT-sources.jar
rpi-ws281x-java-1.1.0-SNAPSHOT.jar

into my library folder with my other jars when I set up a strip

Ws281xLedStrip ring = new Ws281xLedStrip(LED_COUNT, GPIO_PIN, FREQUENCY_HZ,DMA,BRIGHTNESS, PWM_CHANNEL, INVERT, rpi_ws281xConstants.WS2812_STRIP );

I get problems with log4j

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
        at com.github.mbelling.ws281x.Ws281xLedStrip.<clinit>(Ws281xLedStrip.java:20)
        at com.irricurb.device.LightRing.main(LightRing.java:52)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

also if I change my code and have strip number assigned to a local constant I get like 

public class LightRing {
	private static Logger log = Logger.getLogger(LightRing.class);
	
	private static final int LED_COUNT = 12;
	private static final int GPIO_PIN = 10;
	private static final int FREQUENCY_HZ = 800000;
	private static final int DMA = 10;
	private static final int BRIGHTNESS = 255;
	private static final int PWM_CHANNEL = 0;
	private static final boolean INVERT = false;
	private static final int STRIP_TYPE = rpi_ws281xConstants.WS2812_STRIP;

I end up with a unsatisfied link error.

Exception in thread "main" java.lang.UnsatisfiedLinkError: com.github.mbelling.ws281x.jni.rpi_ws281xJNI.WS2811_TARGET_FREQ_get()I
        at com.github.mbelling.ws281x.jni.rpi_ws281xJNI.WS2811_TARGET_FREQ_get(Native Method)
        at com.github.mbelling.ws281x.jni.rpi_ws281xConstants.<clinit>(rpi_ws281xConstants.java:12)
        at com.irricurb.device.LightRing.<clinit>(LightRing.java:33)

is there somewhere in my project new project that i need to drop the log4j jar and ws281x.so?

**Comment by mbelling** [comment]
You will need these two, they were listed in the build.gradle.


    compile 'org.apache.logging.log4j:log4j-api:2.10.0'
    runtime 'org.apache.logging.log4j:log4j-core:2.10.0'

I recommend using a build tool like Maven or Gradle to make things easier for building.  But in this case these two jars should be enough.  You should be able to find them on maven central.  https://search.maven.org.

**Comment by SMT-Ryan** [comment]
I am up and running, additional issues I ran into where environmental to the raspberry pi.  I am going to go and close this.  Thanks again.
