### ISSUE TITLE
Switched to a raspberry pi 3b+ 

### ISSUE THREAD

**Issue by SMT-Ryan** [rpi-ws281x/rpi-ws281x-java#5]
our application was running and able to turn on and off the W2812 LEDs without issue.  we upgraded to a pi 3b+

and  we now encounter a hardware not supported error

WS2811_ERROR_HW_NOT_SUPPORTED
Exception in thread "pool-1-thread-2" java.lang.RuntimeException: Failed to setup lights driver, result code: WS2811_ERROR_HW_NOT_SUPPORTED
at com.github.mbelling.ws281x.Ws281xLedStrip.init(Ws281xLedStrip.java:221)
at com.github.mbelling.ws281x.Ws281xLedStrip.<init>(Ws281xLedStrip.java:99)
at com.irricurb.server.LightRing.<init>(LightRing.java:40)
at com.irricurb.server.LEDRingServer.ledRingManager(LEDRingServer.java:130)
at com.irricurb.server.LEDRingServer.lambda$1(LEDRingServer.java:188)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

based on a bit of searching I think its because my revision number didn't match. not sure if its directly tied to the problem but my rev number is below.

Revision	: a020d3

**Comment by SMT-Ryan** [comment]
did some digging this weekend and it looks like they added support for the raspberry pi to jgraff's code three months ago, changing the commit in the script and recreating the native files fixed the issue.  opened a PR.

**Comment by mbelling** [comment]
Fixed by PR #6
